name: Terraform Workflow

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.8.1"  # Especifica a versão do Terraform

      - name: Load Environment Variables
        run: |
          echo "ACTION_DESTROY=$(cat site/.env | grep ACTION_DESTROY | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Apply or Destroy
        run: |
          if [ "${{ env.ACTION_DESTROY }}" == "true" ]; then
            echo "Destroying infrastructure"
            terraform destroy -auto-approve
          else
            echo "Applying infrastructure"
            terraform apply -auto-approve
