name: Terraform Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - test
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_LOG: DEBUG
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.8.1" 

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Apply or Destroy Terraform
        run: |
          terraform apply --auto-approve
        working-directory: ./terraform             
              
        
        

