name: Terraform Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.8.1" 

      - name: Load Environment Variables
        run: |
          echo "ACTION_DESTROY=true" >> $GITHUB_ENV
        working-directory: ${{ github.workspace }}/site
      
      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ github.workspace }}/terraform
      
      - name: Apply or Destroy Terraform
        run: |
          if [ "$ACTION_DESTROY" == "true" ]; then
            echo "Destroying infrastructure"
            terraform destroy -auto-approve
          else
            echo "Applying infrastructure"
            terraform apply -auto-approve
        working-directory: ${{ github.workspace }}/terraform
        