name: Terraform Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.8.1"  # Assegure-se de que esta versão está correta.

      - name: Load Environment Variables
        run: |
          if [ -f site/.env ]; then
            echo "ACTION_DESTROY=$(grep 'ACTION_DESTROY' site/.env | cut -d '=' -f2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          else
            echo "ERROR: .env file not found, setting default ACTION_DESTROY=false"
            echo "ACTION_DESTROY=false" >> $GITHUB_ENV
          fi
        working-directory: ./

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Apply or Destroy Terraform
        run: |
          if [ "$ACTION_DESTROY" == "true" ]; then
            echo "Destroying infrastructure"
            terraform destroy -auto-approve
          else
            echo "Applying infrastructure"
            terraform apply -auto-approve
        working-directory: ./terraform
